:project:
  :build_root: Build/ceedling/
  :release_build: TRUE
  :test_file_prefix: test_


:paths:
  :test:
    - test/**    # directory where the unit testing are
    - test/support/**
  :source:
    - autosar/**      # directory where the functions to test are
    - autosar/libs/**
    - -:autosar/mcal/regs/** # exclude the registers from the source
    - -:cfg/** 


:defines:
  :test:
    - UTEST
  

:plugins: 
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov
 
:gcov:
  :abort_on_uncovered: true
  :uncovered_ignore_list:
    - main.c #
    - startup.c #
    - autosar/mcal/Nvic/Nvic.c
    - autosar/mcal/Port/Port.c
    - autosar/mcal/Dio/Dio.c
    - autosar/mcal/Gpt/Gpt.c
    - autosar/mcal/Can/Can.c
    - autosar/mcal/Can/Can_Arch.c
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :report_exclude:
    
:tools:
  :test_compiler:
    :executable: gcc
    :name: test_compiler
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGNU_COMPILER
      - -g3
      - -c ${1}
      - -o ${2}
      #- -O0, -pedantic, -Werror, -Wstrict-prototypes, -fsigned-char, -fomit-frame-pointer, -fverbose-asm