# Ceedling configuration to run unit testing with code coverage using GCC compiler and the 
# mcal library, user only has to type make test target from the makefile to run
# all the unit test cases written on files in folder test 
:project:
  :build_root: Build/ceedling/       # Directory where ceedling will place its output
  :use_test_preprocessor: TRUE
  :use_auxiliary_dependencies: TRUE
  :test_file_prefix: test_


# Project paths for test and source and header files
:paths:
  :test:
    - test/**    # directory where the unit testing are
    - test/support/**
  :source:
    - autosar/**      # directory where the functions to test are
    - autosar/libs/**
    - -:autosar/mcal/regs/** # exclude the registers from the source
    - -:cfg/** 


# Global defines applicable only when you run the code using ceedling
:defines:
  :test:
    - TEST           # define the macro UTEST to remove the static qualifier
  

# Plugins to add extra functionality to ceedling, like code coverage and pretty reports
:plugins: 
  :load_paths:
    - "#{Ceedling.load_path}"
  :enabled:
    - stdout_pretty_tests_report
    - module_generator
    - gcov


# enable and configure code coverage 
:gcov:
  :abort_on_uncovered: true
  :uncovered_ignore_list:
    - main.c #
    - startup.c #
    - autosar/mcal/Nvic/Nvic.c
    - autosar/mcal/Port/Port.c
    - autosar/mcal/Dio/Dio.c
    - autosar/mcal/Gpt/Gpt.c
    - autosar/mcal/Can/Can.c
    - autosar/mcal/Can/Can_Arch.c
    - autosar/mcal/Pwm/Pwm.c
    - autosar/mcal/Pwm/Pwm_Arch.c
    - autosar/mcal/Spi/Spi.c
  :utilities:
    - gcovr
  :reports:
    - HtmlDetailed
  :gcovr:
    :report_exclude:
    
:tools:
  :test_compiler:
    :executable: gcc
    :name: test_compiler
    :arguments:
      - -I"$": COLLECTION_PATHS_TEST_TOOLCHAIN_INCLUDE
      - -I"$": COLLECTION_PATHS_TEST_SUPPORT_SOURCE_INCLUDE_VENDOR
      - -D$: COLLECTION_DEFINES_TEST_AND_VENDOR
      - -DGNU_COMPILER
      - -g3
      - -c ${1}
      - -o ${2}
      #- -O0, -pedantic, -Werror, -Wstrict-prototypes, -fsigned-char, -fomit-frame-pointer, -fverbose-asm