version: "3.8"

services:
  jenkins:
    container_name: jenkins
    restart: always
    build: .
    image: local-jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home

volumes:
  jenkins_home:
    driver: local
